[project]
name = "vocabio"
version = "0.1.0"
description = "A personal vocabulary manager built with Django and Python, deployed on Koyeb and connected to a Neon PostgreSQL database. Designed for organising, tracking, and learning English words with a secure and customisable system."
authors = [
    {name = "Alex",email = "alex.nuclearboy@gmail.com"}
]
license = "AGPL-3.0-only"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "django (>=6.1,<7.0)",
    "django-environ (>=0.14.0,<0.15.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)"
]


[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-django (>=4.14.0,<5.0.0)",
    "pylint (>=4.0.7,<5.0.0)",
    "pylint-django (>=2.8.0,<3.0.0)"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py"]

[tool.pylint.main]
load-plugins = ["pylint_django"]
django-settings-module = "config.settings"
py-version = "3.13"
ignore = ["migrations"]
jobs = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint.similarities]
min-similarity-lines = 4
